# Source: Adapted from https://github.com/actions/starter-workflows/blob/main/ci/dotnet.yml
name: .NET Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      env:
          authentication_github_clientId: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTID }}
          authentication_github_clientSecret: ${{ secrets.AUTHENTICATION_GITHUB_CLIENTSECRET }}
      run: dotnet test --no-build --verbosity normal
