name: Label issues
on:
  issues:
    types:
      - reopened
      - opened
jobs:
  label_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: Check issue for keywords and assign labels
        run: |
          # Extract the issue title and body
          ISSUE_TITLE="${{ github.event.issue.title }}"
          ISSUE_BODY="${{ github.event.issue.body }}"

          # Initialize LABELS variable
          LABELS="unlabeled"

          # Check if the issue contains the keyword 'testing' in the title or body
          if echo "$ISSUE_TITLE" | grep -i "testing" || echo "$ISSUE_BODY" | grep -i "testing"; then
            LABELS="$LABELS,testing"
          fi

          # Output the label to be added
          echo "Labels to add: $LABELS"

          # Use the GitHub CLI to add labels
          gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
